name: Build and Deploy Python Static Site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies
      #- name: Install dependencies
       # run: |
          #pip install -r requirements.txt

      # Build the static site (replace with your generator's build command, like mkdocs)
      - name: Build static site
        run: |
          mkdocs build  # Change this if you're using another static generator

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Adjust this to the directory generated by your static site generator
          publish_branch: gh-pages  # This is the branch that GitHub Pages will serve from
