WITH CTE AS (
Select
TO_TIMESTAMP(STARTED_AT),
DATE(TO_TIMESTAMP(STARTED_AT)) As DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)),
DAYNAME(TO_TIMESTAMP(STARTED_AT)),

MONTH(TO_TIMESTAMP(STARTED_AT)),
{{day_type('STARTED_AT')}} as DAY_TYPE,
{{get_seasion('STARTED_AT')}}  as STATION_OF_YEAR
From 
{{ source('demo', 'bike') }}
where STARTED_AT!='started_at'

)


Select * from CTE